<?php
/**
 * Nextcloud - Passman
 *
 * @copyright 2026 Timo Triebensky (timo@binsky.org)
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

declare(strict_types=1);

namespace OCA\Passman\BackupRestore\Restore;

use OCA\Passman\BackupRestore\RestoreResult;
use OCA\Passman\Exception\InvalidBackupException;
use OCP\AppFramework\Db\Entity;
use OCP\AppFramework\Db\QBMapper;
use OCP\DB\Exception;

/**
 * Inserts or updates a single row of a backup section, building the entity generically
 * from the raw snapshot row so that adding a column does not require touching the restore.
 */
final class EntityWriter {

	/**
	 * Inserts the row as a new entity, or updates the given existing row of this instance.
	 *
	 * The mapper `create()` methods cannot be used here:
	 * they generate a new guid and only cover the columns of the live API.
	 *
	 * @param class-string<Entity> $entityClass
	 * @param QBMapper<Entity> $mapper
	 * @param array<string, mixed> $row
	 * @param int|null $existingId id of the row on this instance, null inserts a new one
	 * @throws InvalidBackupException when the row does not match the entity
	 * @throws Exception when the mapper insert or update fails
	 */
	public function store(string $section, QBMapper $mapper, string $entityClass, array $row, ?int $existingId, RestoreResult $result): Entity {
		$entity = $this->buildEntity($section, $entityClass, $row);

		if ($existingId === null) {
			$result->countInserted($section);
			return $mapper->insert($entity);
		}

		$entity->setId($existingId);
		$result->countUpdated($section);
		return $mapper->update($entity);
	}

	/**
	 * Builds an entity from a snapshot row, without its original id:
	 * the id is regenerated by the database so that the artifact stays portable between sqlite, mysql and pgsql.
	 *
	 * @param class-string<Entity> $entityClass
	 * @param array<string, mixed> $row
	 * @throws InvalidBackupException when the row holds a column the entity does not know
	 */
	private function buildEntity(string $section, string $entityClass, array $row): Entity {
		$entity = new $entityClass();

		foreach ($row as $column => $value) {
			if ($column === 'id') {
				continue;
			}
			$setter = 'set' . ucfirst($entity->columnToProperty((string)$column));
			try {
				if ($value === null) {
					// Entity only writes fields whose setter changed the value, and every field of a
					// fresh entity is null: a null column needs a placeholder to become a written NULL
					$entity->{$setter}('');
				}
				$entity->{$setter}($value);
			} catch (\BadFunctionCallException $e) {
				throw new InvalidBackupException(sprintf(
					'The "%s" section of the backup holds the unknown column "%s"', $section, $column
				), 0, $e);
			}
		}

		return $entity;
	}
}
