# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit SQLite

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes-and-matrix:
    uses: ./.github/workflows/phpunit-prepare.yml

  phpunit-sqlite:
    runs-on: ubuntu-latest-low

    needs: changes-and-matrix
    if: needs.changes-and-matrix.outputs.src != 'false'

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.changes-and-matrix.outputs.matrix) }}

    name: SQLite PHP ${{ matrix.php-versions }} Nextcloud ${{ matrix.server-versions }}

    steps:
      - name: Checkout app
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: ./.github/actions/phpunit
        with:
          database: sqlite
          php-version: ${{ matrix.php-versions }}
          server-version: ${{ matrix.server-versions }}
          php-db-extensions: sqlite, pdo_sqlite
          coverage: pcov
          upload-coverage: true

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest-low
    needs: [changes-and-matrix, phpunit-sqlite]

    if: always()

    name: phpunit-sqlite-summary

    steps:
      - name: Summary status
        run: |
          if [ "${{ needs.changes-and-matrix.outputs.src }}" = "false" ]; then
            echo "No relevant changes detected, skipping."
            exit 0
          fi
          if [ "${{ needs.phpunit-sqlite.result }}" != "success" ]; then
            echo "PHPUnit job failed or was cancelled."
            exit 1
          fi
