# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit MySQL

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes-and-matrix:
    uses: ./.github/workflows/phpunit-prepare.yml
    with:
      extra-matrix: '{"mysql-versions": ["8.4"]}'

  phpunit-mysql:
    runs-on: ubuntu-latest-low

    needs: changes-and-matrix
    if: needs.changes-and-matrix.outputs.src != 'false'

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.changes-and-matrix.outputs.matrix) }}

    name: MySQL ${{ matrix.mysql-versions }} PHP ${{ matrix.php-versions }} Nextcloud ${{ matrix.server-versions }}

    services:
      mysql:
        image: ghcr.io/nextcloud/continuous-integration-mysql-${{ matrix.mysql-versions }}:latest # zizmor: ignore[unpinned-images]
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 10

    steps:
      - name: Checkout app
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: ./.github/actions/phpunit
        with:
          database: mysql
          php-version: ${{ matrix.php-versions }}
          server-version: ${{ matrix.server-versions }}
          php-db-extensions: mysql, pdo_mysql
          coverage: none
          phpunit-args: -- --no-coverage

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest-low
    needs: [changes-and-matrix, phpunit-mysql]

    if: always()

    name: phpunit-mysql-summary

    steps:
      - name: Summary status
        run: |
          if [ "${{ needs.changes-and-matrix.outputs.src }}" = "false" ]; then
            echo "No relevant changes detected, skipping."
            exit 0
          fi
          if [ "${{ needs.phpunit-mysql.result }}" != "success" ]; then
            echo "PHPUnit job failed or was cancelled."
            exit 1
          fi
